// <auto-generated />
using System;
using ArchEcommerceSystem.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArchEcommerceSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260326181635_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArchEcommerceSystem.Core.Aggregates.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ArchEcommerceSystem.Core.Aggregates.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("ArchEcommerceSystem.Core.Aggregates.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("ArchEcommerceSystem.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ErrorOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("ArchEcommerceSystem.Core.Aggregates.Cliente", b =>
                {
                    b.OwnsOne("ArchEcommerceSystem.Core.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Email");

                            b1.HasKey("ClienteId");

                            b1.ToTable("Clientes");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.Navigation("Email")
                        .IsRequired();
                });

            modelBuilder.Entity("ArchEcommerceSystem.Core.Aggregates.Pedido", b =>
                {
                    b.OwnsOne("ArchEcommerceSystem.Core.ValueObjects.Money", "ValorTotal", b1 =>
                        {
                            b1.Property<Guid>("PedidoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("ValorTotal");

                            b1.HasKey("PedidoId");

                            b1.ToTable("Pedidos");

                            b1.WithOwner()
                                .HasForeignKey("PedidoId");
                        });

                    b.OwnsMany("ArchEcommerceSystem.Core.Entities.ItemPedido", "Itens", b1 =>
                        {
                            b1.Property<Guid>("PedidoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("ProdutoId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("PedidoId", "Id");

                            b1.ToTable("ItemPedido");

                            b1.WithOwner()
                                .HasForeignKey("PedidoId");

                            b1.OwnsOne("ArchEcommerceSystem.Core.ValueObjects.Money", "PrecoUnitario", b2 =>
                                {
                                    b2.Property<Guid>("ItemPedidoPedidoId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("ItemPedidoId")
                                        .HasColumnType("int");

                                    b2.Property<decimal>("Value")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("PrecoUnitario");

                                    b2.HasKey("ItemPedidoPedidoId", "ItemPedidoId");

                                    b2.ToTable("ItemPedido");

                                    b2.WithOwner()
                                        .HasForeignKey("ItemPedidoPedidoId", "ItemPedidoId");
                                });

                            b1.OwnsOne("ArchEcommerceSystem.Core.ValueObjects.Quantidade", "Quantidade", b2 =>
                                {
                                    b2.Property<Guid>("ItemPedidoPedidoId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("ItemPedidoId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Value")
                                        .HasColumnType("int")
                                        .HasColumnName("Quantidade");

                                    b2.HasKey("ItemPedidoPedidoId", "ItemPedidoId");

                                    b2.ToTable("ItemPedido");

                                    b2.WithOwner()
                                        .HasForeignKey("ItemPedidoPedidoId", "ItemPedidoId");
                                });

                            b1.Navigation("PrecoUnitario")
                                .IsRequired();

                            b1.Navigation("Quantidade")
                                .IsRequired();
                        });

                    b.Navigation("Itens");

                    b.Navigation("ValorTotal")
                        .IsRequired();
                });

            modelBuilder.Entity("ArchEcommerceSystem.Core.Aggregates.Produto", b =>
                {
                    b.OwnsOne("ArchEcommerceSystem.Core.ValueObjects.Money", "Preco", b1 =>
                        {
                            b1.Property<Guid>("ProdutoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Preco");

                            b1.HasKey("ProdutoId");

                            b1.ToTable("Produtos");

                            b1.WithOwner()
                                .HasForeignKey("ProdutoId");
                        });

                    b.Navigation("Preco")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
