version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong!Pass123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    # networks:
    #   - ecommerce-network

  api:
    build:
      context: .
      dockerfile: ArchEcommerceSystem.WebApi/Dockerfile
    container_name: ecommerce-api
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=EcommerceDb;User Id=sa;Password=YourStrong!Pass123;TrustServerCertificate=True
      - Kafka__BootstrapServers={SEU_HOST_KAFKA:PORTA}
    # networks:
    #   - ecommerce-network

# networks:
#   ecommerce-network:
#     external: true